### ISSUE TITLE
conduit-iconv-0.1.1.0 missing hsiconv.h

### ISSUE THREAD

**Issue by juhp** [sdroege/conduit-iconv#1]
conduit-iconv fails to build:

```
Configuring conduit-iconv-0.1.1.0...
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: hsiconv.h
```

I think you need to add hsiconv.h to your .cabal file.

**Comment by sdroege** [comment]
https://github.com/fpco/stackage/pull/1016#issuecomment-161547653

I think this is a problem wherever this is tried to be built. Seems no iconv.h is available there. Can you confirm? What platform is this built on?

**Comment by juhp** [comment]
There is no .h file in the tarball.  I think it should be in c-sources.

**Comment by sdroege** [comment]
Ah, that makes sense. Thanks!

**Comment by juhp** [comment]
Can you update here when you make a new release? :)

**Comment by sdroege** [comment]
Done already, there's 0.1.1.1 on hackage now

**Comment by juhp** [comment]
Thank you!
